FROM atanistra/base
MAINTAINER atanistra <artur.tanistra@gmail.com>

RUN mkdir -p /usr/selenium && \
    wget --no-verbose http://selenium-release.storage.googleapis.com/2.50/selenium-server-standalone-2.50.1.jar -O /usr/selenium/selenium-server-standalone.jar



